/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author Usuario
 */
public class calculadora extends javax.swing.JFrame {

    /**
     * Creates new form calculadora
     */
    public float primernumero;
    public float segundonumero;
    public String Operator;
    
    
    
    
    
    public calculadora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        pnl_calculadora_general = new javax.swing.JPanel();
        txt_resultado_de_calculadora = new javax.swing.JTextField();
        btn_numero_seis = new javax.swing.JButton();
        btn_numero_siete = new javax.swing.JButton();
        btn_numero_ocho = new javax.swing.JButton();
        btn_numero_nueve = new javax.swing.JButton();
        btn_signo_resta = new javax.swing.JButton();
        btn_numero_uno = new javax.swing.JButton();
        btn_signo_multiplicacion = new javax.swing.JButton();
        btn_numero_dos = new javax.swing.JButton();
        btn_numero_cero = new javax.swing.JButton();
        btn_numero_tres = new javax.swing.JButton();
        btn_punto = new javax.swing.JButton();
        btn_signo_suma = new javax.swing.JButton();
        btn_signo_igual = new javax.swing.JButton();
        btn_numero_cuatro = new javax.swing.JButton();
        btn_signo_division = new javax.swing.JButton();
        btn_numero_cinco = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jm_opciones = new javax.swing.JMenu();
        jmenu_nuevo = new javax.swing.JMenu();
        jmenu_reiniciar = new javax.swing.JMenuItem();
        jmenu_historial = new javax.swing.JMenu();
        jmenu_operaciones = new javax.swing.JMenuItem();
        jmenu_ayuda = new javax.swing.JMenu();
        jmenu_manual_de_usuario = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        jMenuItem1.setText("opciones");
        jPopupMenu1.add(jMenuItem1);

        jMenuItem2.setText("Ayuda");
        jPopupMenu2.add(jMenuItem2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txt_resultado_de_calculadora.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_resultado_de_calculadora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_resultado_de_calculadoraActionPerformed(evt);
            }
        });

        btn_numero_seis.setText("6");
        btn_numero_seis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_numero_seisActionPerformed(evt);
            }
        });

        btn_numero_siete.setText("7");
        btn_numero_siete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_numero_sieteActionPerformed(evt);
            }
        });

        btn_numero_ocho.setText("8");
        btn_numero_ocho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_numero_ochoActionPerformed(evt);
            }
        });

        btn_numero_nueve.setText("9");
        btn_numero_nueve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_numero_nueveActionPerformed(evt);
            }
        });

        btn_signo_resta.setText("-");
        btn_signo_resta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_signo_restaActionPerformed(evt);
            }
        });

        btn_numero_uno.setText("1");
        btn_numero_uno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_numero_unoActionPerformed(evt);
            }
        });

        btn_signo_multiplicacion.setText("*");
        btn_signo_multiplicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_signo_multiplicacionActionPerformed(evt);
            }
        });

        btn_numero_dos.setText("2");
        btn_numero_dos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_numero_dosActionPerformed(evt);
            }
        });

        btn_numero_cero.setText("0");
        btn_numero_cero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_numero_ceroActionPerformed(evt);
            }
        });

        btn_numero_tres.setText("3");
        btn_numero_tres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_numero_tresActionPerformed(evt);
            }
        });

        btn_punto.setText(".");
        btn_punto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_puntoActionPerformed(evt);
            }
        });

        btn_signo_suma.setText("+");
        btn_signo_suma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_signo_sumaActionPerformed(evt);
            }
        });

        btn_signo_igual.setText("=");
        btn_signo_igual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_signo_igualActionPerformed(evt);
            }
        });

        btn_numero_cuatro.setText("4");
        btn_numero_cuatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_numero_cuatroActionPerformed(evt);
            }
        });

        btn_signo_division.setText("/");
        btn_signo_division.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_signo_divisionActionPerformed(evt);
            }
        });

        btn_numero_cinco.setText("5");
        btn_numero_cinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_numero_cincoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_calculadora_generalLayout = new javax.swing.GroupLayout(pnl_calculadora_general);
        pnl_calculadora_general.setLayout(pnl_calculadora_generalLayout);
        pnl_calculadora_generalLayout.setHorizontalGroup(
            pnl_calculadora_generalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_calculadora_generalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_calculadora_generalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_calculadora_generalLayout.createSequentialGroup()
                        .addGroup(pnl_calculadora_generalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_numero_uno, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_numero_cuatro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_numero_siete, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_numero_cero, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnl_calculadora_generalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnl_calculadora_generalLayout.createSequentialGroup()
                                .addComponent(btn_punto, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_signo_igual, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(btn_signo_division, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnl_calculadora_generalLayout.createSequentialGroup()
                                .addComponent(btn_numero_dos, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_numero_tres, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_signo_suma, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnl_calculadora_generalLayout.createSequentialGroup()
                                .addComponent(btn_numero_cinco, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_numero_seis, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(btn_signo_resta, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnl_calculadora_generalLayout.createSequentialGroup()
                                .addComponent(btn_numero_ocho, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_numero_nueve, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(btn_signo_multiplicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(txt_resultado_de_calculadora, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl_calculadora_generalLayout.setVerticalGroup(
            pnl_calculadora_generalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_calculadora_generalLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(txt_resultado_de_calculadora, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_calculadora_generalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_numero_uno, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_numero_dos, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_numero_tres, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_signo_suma, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnl_calculadora_generalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_numero_cuatro, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_numero_cinco, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_numero_seis, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_signo_resta, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnl_calculadora_generalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_numero_siete, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_numero_ocho, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_numero_nueve, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_signo_multiplicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnl_calculadora_generalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_numero_cero, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_punto, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_signo_igual, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_signo_division, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jm_opciones.setText("Opciones");

        jmenu_nuevo.setText("Nuevo");

        jmenu_reiniciar.setText("Reiniciar");
        jmenu_reiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenu_reiniciarActionPerformed(evt);
            }
        });
        jmenu_nuevo.add(jmenu_reiniciar);

        jm_opciones.add(jmenu_nuevo);

        jmenu_historial.setText("Historial");

        jmenu_operaciones.setText("Historial de operaciones");
        jmenu_operaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenu_operacionesActionPerformed(evt);
            }
        });
        jmenu_historial.add(jmenu_operaciones);

        jm_opciones.add(jmenu_historial);

        jMenuBar1.add(jm_opciones);

        jmenu_ayuda.setText("Ayuda");
        jmenu_ayuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenu_ayudaActionPerformed(evt);
            }
        });

        jmenu_manual_de_usuario.setText("Manual de Usuario");
        jmenu_manual_de_usuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmenu_manual_de_usuarioMouseClicked(evt);
            }
        });
        jmenu_manual_de_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenu_manual_de_usuarioActionPerformed(evt);
            }
        });

        jMenuItem3.setText("Manual");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jmenu_manual_de_usuario.add(jMenuItem3);

        jmenu_ayuda.add(jmenu_manual_de_usuario);

        jMenuBar1.add(jmenu_ayuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnl_calculadora_general, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(11, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnl_calculadora_general, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_numero_cincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_numero_cincoActionPerformed
        // TODO add your handling code here:
        this.txt_resultado_de_calculadora.setText(this.txt_resultado_de_calculadora.getText()+"5");
    }//GEN-LAST:event_btn_numero_cincoActionPerformed

    private void btn_numero_cuatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_numero_cuatroActionPerformed
        // TODO add your handling code here:
        this.txt_resultado_de_calculadora.setText(this.txt_resultado_de_calculadora.getText()+"4");
    }//GEN-LAST:event_btn_numero_cuatroActionPerformed

    private void btn_signo_sumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_signo_sumaActionPerformed
        // TODO add your handling code here:
        this.primernumero=Float.parseFloat(this.txt_resultado_de_calculadora.getText());
        this.Operator="+";
        this.txt_resultado_de_calculadora.setText("");
    }//GEN-LAST:event_btn_signo_sumaActionPerformed

    private void btn_puntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_puntoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_puntoActionPerformed

    private void btn_numero_tresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_numero_tresActionPerformed
        // TODO add your handling code here:
        this.txt_resultado_de_calculadora.setText(this.txt_resultado_de_calculadora.getText()+"3");
    }//GEN-LAST:event_btn_numero_tresActionPerformed

    private void btn_numero_ceroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_numero_ceroActionPerformed
        // TODO add your handling code here:
        this.txt_resultado_de_calculadora.setText(this.txt_resultado_de_calculadora.getText()+"0");
    }//GEN-LAST:event_btn_numero_ceroActionPerformed

    private void btn_numero_dosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_numero_dosActionPerformed
        // TODO add your handling code here:
        this.txt_resultado_de_calculadora.setText(this.txt_resultado_de_calculadora.getText()+"2");
    }//GEN-LAST:event_btn_numero_dosActionPerformed

    private void btn_numero_unoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_numero_unoActionPerformed
        // TODO add your handling code here:
        this.txt_resultado_de_calculadora.setText(this.txt_resultado_de_calculadora.getText()+"1");
    }//GEN-LAST:event_btn_numero_unoActionPerformed

    private void btn_numero_nueveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_numero_nueveActionPerformed
        // TODO add your handling code here:
        this.txt_resultado_de_calculadora.setText(this.txt_resultado_de_calculadora.getText()+"9");
    }//GEN-LAST:event_btn_numero_nueveActionPerformed

    private void btn_numero_ochoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_numero_ochoActionPerformed
        // TODO add your handling code here:
        this.txt_resultado_de_calculadora.setText(this.txt_resultado_de_calculadora.getText()+"8");
    }//GEN-LAST:event_btn_numero_ochoActionPerformed

    private void btn_numero_sieteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_numero_sieteActionPerformed
        // TODO add your handling code here:
        this.txt_resultado_de_calculadora.setText(this.txt_resultado_de_calculadora.getText()+"7");
    }//GEN-LAST:event_btn_numero_sieteActionPerformed

    private void btn_numero_seisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_numero_seisActionPerformed
        // TODO add your handling code here:
        this.txt_resultado_de_calculadora.setText(this.txt_resultado_de_calculadora.getText()+"6");
    }//GEN-LAST:event_btn_numero_seisActionPerformed

    private void txt_resultado_de_calculadoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_resultado_de_calculadoraActionPerformed
        // TODO add your handling code here:
        this.txt_resultado_de_calculadora.setHorizontalAlignment(HEIGHT);
        
    }//GEN-LAST:event_txt_resultado_de_calculadoraActionPerformed

    private void btn_signo_igualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_signo_igualActionPerformed
        // TODO add your handling code here:
        this.segundonumero=Float.parseFloat(this.txt_resultado_de_calculadora.getText());
        
        
        switch(this.Operator){
            case"+":this.txt_resultado_de_calculadora.setText(Float.toString(this.primernumero+this.segundonumero));
        }
        switch(this.Operator){
            case"-":this.txt_resultado_de_calculadora.setText(Float.toString(this.primernumero-this.segundonumero));
        }
        switch(this.Operator){
            case"*":this.txt_resultado_de_calculadora.setText(Float.toString(this.primernumero*this.segundonumero));
        }
        switch(this.Operator){
            case"/":this.txt_resultado_de_calculadora.setText(Float.toString(this.primernumero/this.segundonumero));
        }
        
    }//GEN-LAST:event_btn_signo_igualActionPerformed

    private void btn_signo_restaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_signo_restaActionPerformed
        // TODO add your handling code here:
        this.primernumero=Float.parseFloat(this.txt_resultado_de_calculadora.getText());
        this.Operator="-";
        this.txt_resultado_de_calculadora.setText("");
    }//GEN-LAST:event_btn_signo_restaActionPerformed

    private void btn_signo_multiplicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_signo_multiplicacionActionPerformed
        // TODO add your handling code here:
        this.primernumero=Float.parseFloat(this.txt_resultado_de_calculadora.getText());
        this.Operator="*";
        this.txt_resultado_de_calculadora.setText("");
    }//GEN-LAST:event_btn_signo_multiplicacionActionPerformed

    private void btn_signo_divisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_signo_divisionActionPerformed
        // TODO add your handling code here:
        this.primernumero=Float.parseFloat(this.txt_resultado_de_calculadora.getText());
        this.Operator="/";
        this.txt_resultado_de_calculadora.setText("");
    }//GEN-LAST:event_btn_signo_divisionActionPerformed

    private void jmenu_manual_de_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenu_manual_de_usuarioActionPerformed
        // TODO add your handling code here:
        Jframe2 oforma = new Jframe2();
        oforma.setVisible(true);
    }//GEN-LAST:event_jmenu_manual_de_usuarioActionPerformed

    private void jmenu_reiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenu_reiniciarActionPerformed
        // TODO add your handling code here:
        this.txt_resultado_de_calculadora.setText("");
    }//GEN-LAST:event_jmenu_reiniciarActionPerformed

    private void jmenu_manual_de_usuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmenu_manual_de_usuarioMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jmenu_manual_de_usuarioMouseClicked

    private void jmenu_operacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenu_operacionesActionPerformed
        // TODO add your handling code here:
        Jframe3 oforma = new Jframe3();
        oforma.setVisible(true);
    }//GEN-LAST:event_jmenu_operacionesActionPerformed

    private void jmenu_ayudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenu_ayudaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmenu_ayudaActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
         Jframe2 oforma = new Jframe2();
        oforma.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_numero_cero;
    private javax.swing.JButton btn_numero_cinco;
    private javax.swing.JButton btn_numero_cuatro;
    private javax.swing.JButton btn_numero_dos;
    private javax.swing.JButton btn_numero_nueve;
    private javax.swing.JButton btn_numero_ocho;
    private javax.swing.JButton btn_numero_seis;
    private javax.swing.JButton btn_numero_siete;
    private javax.swing.JButton btn_numero_tres;
    private javax.swing.JButton btn_numero_uno;
    private javax.swing.JButton btn_punto;
    private javax.swing.JButton btn_signo_division;
    private javax.swing.JButton btn_signo_igual;
    private javax.swing.JButton btn_signo_multiplicacion;
    private javax.swing.JButton btn_signo_resta;
    private javax.swing.JButton btn_signo_suma;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JMenu jm_opciones;
    private javax.swing.JMenu jmenu_ayuda;
    private javax.swing.JMenu jmenu_historial;
    private javax.swing.JMenu jmenu_manual_de_usuario;
    private javax.swing.JMenu jmenu_nuevo;
    private javax.swing.JMenuItem jmenu_operaciones;
    private javax.swing.JMenuItem jmenu_reiniciar;
    private javax.swing.JPanel pnl_calculadora_general;
    private javax.swing.JTextField txt_resultado_de_calculadora;
    // End of variables declaration//GEN-END:variables
}
